generator bit if_exp(int w){
    return {|(w%2==0) (|| | &&) (w (< | > | <= | >= | == | !=) ?? | 1 | 0)|}; // also gives correct program
}
int even_greater_2(int wgt)
{    
    if (if_exp(wgt))
        return {|1|0|};
    else
        return {|1|0|};
}
int even_greater_2_correct(int wgt)
{    
    if (wgt%2==0&&wgt>2)
        return 1;
    else
        return 0;
}
harness void main(int x){
    assert even_greater_2(x) == even_greater_2_correct(x);
}
