generator bit if_exp(int w){
    return {|(w%2==0) (|| | &&) (w (< | > | <= | >= | == | !=) 2 | 1 | 0)|}; // gives correct program
}
int even_not_2(int w)
{
    if(if_exp(w))
    {
        return {|1|0|};
    }
    else{
        return {|1|0|};
    }
}
int even_not_2_correct(int w)
{
    if(w % 2 == 0 && w != 2)
    {
        return 1;
    }
    else{
        return 0;
    }
}
harness void main(int x){
    assert even_not_2(x) == even_not_2_correct(x);
}
